name: 'Downgrade Julia compat entries'
description: 'Restricts the compat entries in Project.toml so that only the oldest versions are installed.'
inputs:
  skip:
    description: 'Comma-separated list of packages to not downgrade.'
    default: ''
  strict:
    description: 'true, false or v0. Default: v0.'
    default: 'v0'
  projects:
    description: 'Comma-separated list of Julia projects to modify.'
    default: '.'
runs:
  using: "composite"
  steps:
    - run: julia "${{ github.action_path }}/downgrade.jl" "${{ inputs.skip }}" "${{ inputs.strict }}" "${{ inputs.projects }}"
      shell: bash
branding:
  icon: trending-down
  color: purple
