name: 'Downgrade Julia compat entries'
description: 'Uses Resolver.jl to find and install minimal compatible versions of dependencies.'
inputs:
  skip:
    description: 'Comma-separated list of packages to not downgrade.'
    default: ''
  projects:
    description: 'Comma-separated list of Julia projects to resolve.'
    default: '.'
  mode:
    description: 'Downgrade mode: deps (direct dependencies), alldeps (deps + weakdeps), all (all packages)'
    default: 'deps'
  julia_version:
    description: 'Julia version to use with resolver (default: 1.11)'
    default: '1.11'
runs:
  using: "composite"
  steps:
    - run: julia "${{ github.action_path }}/downgrade.jl" "${{ inputs.skip }}" "${{ inputs.projects }}" "${{ inputs.mode }}" "${{ inputs.julia_version }}"
      shell: bash
branding:
  icon: trending-down
  color: purple
